export const KeyInfo = {
  "esc": {"dimension": 1, "ledId": 1},
  "escapeToF1Spacer": {"dimension": 1},
  "f1": {"dimension": 1, "ledId": 2},
  "f2": {"dimension": 1, "ledId": 3}, 
  "f3": {"dimension": 1, "ledId": 4}, 
  "f4ToF5Spacer": {"dimension": 0.5},
  "f4": {"dimension": 1, "ledId": 5}, 
  "f5": {"dimension": 1, "ledId": 6}, 
  "f6": {"dimension": 1, "ledId": 7}, 
  "f7": {"dimension": 1, "ledId": 8}, 
  "f8": {"dimension": 1, "ledId": 9}, 
  "f8ToF9Spacer": {"dimension": 0.5},
  "f9": {"dimension": 1, "ledId": 10},
  "f10": {"dimension": 1, "ledId": 11},
  "f11": {"dimension": 1, "ledId": 12},
  "f12": {"dimension": 1, "ledId": 13},
  "f12ToPrintSpacer": {"dimension": 0.5},
  "print": {"dimension": 1, "ledId": 14},
  "scrollLock": {"dimension": 1, "ledId": 15, "label": "ScrLck"},
  "pause": {"dimension": 1, "ledId": 16},

  "graveAccent": {"dimension": 1, "ledId": 17, "label": "~ `"},
  "one": {"dimension": 1, "ledId": 18, "label": "! 1"},
  "two": {"dimension": 1, "ledId": 19, "label": "@ 2"},
  "three": {"dimension": 1, "ledId": 20, "label": "# 3"},
  "four": {"dimension": 1, "ledId": 21, "label": "$ 4"},
  "five": {"dimension": 1, "ledId": 22, "label": "% 5"},
  "six": {"dimension": 1, "ledId": 23, "label": "^ 6"},
  "seven": {"dimension": 1, "ledId": 24, "label": "& 7"},
  "eight": {"dimension": 1, "ledId": 25, "label": "* 8"},
  "nine": {"dimension": 1, "ledId": 26, "label": "( 9"},
  "zero": {"dimension": 1, "ledId": 27, "label": ") 0"},
  "hypen": {"dimension": 1, "ledId": 28, "label": "_ -"},
  "equals": {"dimension": 1, "ledId": 29, "label": "+ ="},
  "backspace": {"dimension": 2, "ledId": 30},
  "backspaceToInsertSpacer": {"dimension": 0.5},
  "insert": {"dimension": 1, "ledId": 31},
  "home": {"dimension": 1, "ledId": 32},
  "pageUp": {"dimension": 1, "ledId": 33, "label": "PgUp"},

  "tab": {"dimension": 1.5, "ledId": 34},
  "q": {"dimension": 1, "ledId": 35},
  "w": {"dimension": 1, "ledId": 36},
  "e": {"dimension": 1, "ledId": 37},
  "r": {"dimension": 1, "ledId": 38},
  "t": {"dimension": 1, "ledId": 39},
  "y": {"dimension": 1, "ledId": 40},
  "u": {"dimension": 1, "ledId": 41},
  "i": {"dimension": 1, "ledId": 42},
  "o": {"dimension": 1, "ledId": 43},
  "p": {"dimension": 1, "ledId": 44},
  "leftBracket": {"dimension": 1, "ledId": 45, "label": "{ ["},
  "rightBracket": {"dimension": 1, "ledId": 46, "label": "} ]"},
  "fowardSlash": {"dimension": 1.5, "ledId": 47, "label": "| \\"},
  "fowardSlashToDeleteSpacer": {"dimension": 0.5},
  "delete": {"dimension": 1, "ledId": 48},
  "end": {"dimension": 1, "ledId": 49},
  "pageDown": {"dimension": 1, "ledId": 50, "label": "PgUp"},

  "capsLock": {"dimension": 1.75, "ledId": 51},
  "a": {"dimension": 1, "ledId": 52},
  "s": {"dimension": 1, "ledId": 53},
  "d": {"dimension": 1, "ledId": 54},
  "f": {"dimension": 1, "ledId": 55},
  "g": {"dimension": 1, "ledId": 56},
  "h": {"dimension": 1, "ledId": 57},
  "j": {"dimension": 1, "ledId": 58},
  "k": {"dimension": 1, "ledId": 59},
  "l": {"dimension": 1, "ledId": 60},
  "semicolon": {"dimension": 1, "ledId": 61, "label": ": ;"},
  "apostrophe": {"dimension": 1, "ledId": 62, "label": "\" '"},
  "enter": {"dimension": 2.25, "ledId": 63},
  "enterToInfinity": {"dimension": 3.5},

  "leftShift": {"dimension": 2.25, "ledId": 64, "label": "Shift"},
  "z": {"dimension": 1, "ledId": 65},
  "x": {"dimension": 1, "ledId": 66},
  "c": {"dimension": 1, "ledId": 67},
  "v": {"dimension": 1, "ledId": 68},
  "b": {"dimension": 1, "ledId": 69},
  "n": {"dimension": 1, "ledId": 70},
  "m": {"dimension": 1, "ledId": 71},
  "comma": {"dimension": 1, "ledId": 72, "label": "< ,"},
  "period": {"dimension": 1, "ledId": 73, "label": "> ."},
  "backslash": {"dimension": 1, "ledId": 74, "label": "? /"},
  "rightShift": {"dimension": 2.75, "ledId": 75},
  "rightShiftToUpSpacer": {"dimension": 1.5},
  "up": {"dimension": 1, "ledId": 76},
  "upToInfinitySpacer": {"dimension": 1},

  "leftControl": {"dimension": 1.25, "ledId": 77, "label": "Ctrl"},
  "super": {"dimension": 1.25, "ledId": 78},
  "leftAlt": {"dimension": 1.25, "ledId": 79, "label": "Alt"},
  "space": {"dimension": 6.25, "ledId": 80, "label": " "},
  "rightAlt": {"dimension": 1.25, "ledId": 81, "label": "Alt"},
  "function": {"dimension": 1.25, "ledId": 82},
  "menu": {"dimension": 1.25, "ledId": 83},
  "rightControl": {"dimension": 1.25, "ledId": 84, "label": "Ctrl"},
  "rightControlToLeftSpacer": {"dimension": 0.5},
  "left": {"dimension": 1, "ledId": 85},
  "down": {"dimension": 1, "ledId": 86},
  "right": {"dimension": 1, "ledId": 87},

  "side1": {"ledId": 88},
  "side2": {"ledId": 89},
  "side3": {"ledId": 90},
  "side4": {"ledId": 91},
  "side5": {"ledId": 92},
  "side6": {"ledId": 93},
  "side7": {"ledId": 94},
  "side8": {"ledId": 95},
  "side9": {"ledId": 96},
  "side10": {"ledId": 97},
  "side11": {"ledId": 98},
  "side12": {"ledId": 99},
  "side13": {"ledId": 100},
  "side14": {"ledId": 101},
  "side15": {"ledId": 102},
  "side16": {"ledId": 103},
  "side17": {"ledId": 104},
  "side18": {"ledId": 105},
  "side19": {"ledId": 106},
  "side20": {"ledId": 107},
  "side21": {"ledId": 108},
  "side22": {"ledId": 109},
  "side23": {"ledId": 110},
  "side24": {"ledId": 111},
  "side25": {"ledId": 112},
  "side26": {"ledId": 113},
  "side27": {"ledId": 114},
  "side28": {"ledId": 115},
  "side29": {"ledId": 116},
  "side30": {"ledId": 117},
  "side31": {"ledId": 118},
  "side32": {"ledId": 119}
}

export const RowLayout = {
  "R0": [
    "esc", "escapeToF1Spacer", 
    "f1", "f2", "f3", "f4", "f4ToF5Spacer", 
    "f5", "f6", "f7", "f8", "f8ToF9Spacer",
    "f9", "f10", "f11", "f12", "f12ToPrintSpacer",
    "print", "scrollLock", "pause"
  ],
  "R1": [
    "graveAccent", "one", "two", "three", "four", "five", "six", "seven", 
    "eight", "nine", "zero", "hypen", "equals", "backspace", "backspaceToInsertSpacer",
    "insert", "home", "pageUp"
  ],
  "R2": [
    "tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", 
    "leftBracket", "rightBracket", "fowardSlash", "fowardSlashToDeleteSpacer",
    "delete", "end", "pageDown"
  ],
  "R3": [
    "capsLock", "a", "s", "d", "f", "g", "h", "j", "k", "l", 
    "semicolon", "apostrophe", "enter", "enterToInfinity"
  ],
  "R4": [
    "leftShift", "z", "x", "c", "v", "b", "n", "m", 
    "comma", "period", "backslash", "rightShift", "rightShiftToUpSpacer", 
    "up", "upToInfinitySpacer"
  ],
  "R5": [
    "leftControl", "super", "leftAlt", "space", "rightAlt", "function", "menu",
    "rightControl", "rightControlToLeftSpacer", "left", "down", "right"
  ]
}